apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: team
spec:
  project: team
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook
  destination:
    name: in-cluster
    namespace: team
  syncPolicy:
    automated:
      prune: true
