apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  namespace: team
spec:
  # project: default # not allowed
  project: team
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook
  destination:
    name: in-cluster
    # namespace: argocd # not allowed
    namespace: team
  syncPolicy:
    automated:
      prune: true
